// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abymjoxmtdgralfzswnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFieW1qb3htdGRncmFsZnpzd25rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjIwMTgsImV4cCI6MjA3MDE5ODAxOH0.uUcWuv42TibfxxKzPIFhpLVeCzVuW1qiYVT1qRCo9vE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});